import type { StructuredMemory } from "./extractor";
import type { ConversationAnalysis } from "./analyzer";

export function generateMarkdownReport(
    memory: StructuredMemory,
    analysis: ConversationAnalysis | null,
    title?: string
): string {
    const reportTitle = title || "AI Conversation Analysis Report";
    const date = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric"
    });

    let markdown = `# ${reportTitle}

*Generated on ${date}*

---

## Table of Contents

1. [Executive Summary](#executive-summary)
2. [Detailed Analysis](#detailed-analysis)
3. [Key Points](#key-points)
4. [Structured Memory](#structured-memory)
   - [Overview](#overview)
   - [Topics Discussed](#topics-discussed)
   - [Decisions Made](#decisions-made)
   - [Important Points](#important-points)
   - [Code References](#code-references)
   - [Assumptions](#assumptions)
   - [Unresolved Questions](#unresolved-questions)
   - [Action Items](#action-items)

---

`;

    // Executive Summary
    markdown += `## Executive Summary\n\n`;
    if (analysis?.summary) {
        markdown += `${analysis.summary}\n\n`;
    } else {
        markdown += `*No executive summary available.*\n\n`;
    }

    // Detailed Analysis
    markdown += `## Detailed Analysis\n\n`;
    if (analysis?.detailed) {
        markdown += `${analysis.detailed}\n\n`;
    } else {
        markdown += `*No detailed analysis available.*\n\n`;
    }

    // Key Points
    markdown += `## Key Points\n\n`;
    if (analysis?.keyPoints && analysis.keyPoints.length > 0) {
        analysis.keyPoints.forEach((point, index) => {
            markdown += `${index + 1}. ${point}\n`;
        });
        markdown += `\n`;
    } else {
        markdown += `*No key points extracted.*\n\n`;
    }

    // Structured Memory
    markdown += `## Structured Memory\n\n`;

    // Overview
    markdown += `### Overview\n\n`;
    if (memory.overview) {
        markdown += `${memory.overview}\n\n`;
    } else {
        markdown += `*No overview available.*\n\n`;
    }

    // Topics Discussed
    if (memory.topics.length > 0) {
        markdown += `### Topics Discussed\n\n`;
        memory.topics.forEach(topic => {
            markdown += `- ${topic}\n`;
        });
        markdown += `\n`;
    }

    // Decisions Made
    if (memory.decisions.length > 0) {
        markdown += `### Decisions Made\n\n`;
        memory.decisions.forEach(decision => {
            markdown += `- ${decision}\n`;
        });
        markdown += `\n`;
    }

    // Important Points
    if (memory.important_points.length > 0) {
        markdown += `### Important Points\n\n`;
        memory.important_points.forEach(point => {
            markdown += `- ${point}\n`;
        });
        markdown += `\n`;
    }

    // Code References
    if (memory.code_references.length > 0) {
        markdown += `### Code References\n\n`;
        memory.code_references.forEach(ref => {
            // Check if it looks like a code block or file reference
            if (ref.includes('```') || ref.includes('`')) {
                markdown += `- ${ref}\n`;
            } else {
                markdown += `- \`${ref}\`\n`;
            }
        });
        markdown += `\n`;
    }

    // Assumptions
    if (memory.assumptions.length > 0) {
        markdown += `### Assumptions\n\n`;
        memory.assumptions.forEach(assumption => {
            markdown += `- ${assumption}\n`;
        });
        markdown += `\n`;
    }

    // Unresolved Questions
    if (memory.unresolved_questions.length > 0) {
        markdown += `### Unresolved Questions\n\n`;
        memory.unresolved_questions.forEach(question => {
            markdown += `- ${question}\n`;
        });
        markdown += `\n`;
    }

    // Action Items
    if (memory.action_items.length > 0) {
        markdown += `### Action Items\n\n`;
        memory.action_items.forEach(item => {
            markdown += `- [ ] ${item}\n`;
        });
        markdown += `\n`;
    }

    // Footer
    markdown += `---

*This report was generated by the AI Conversation Portability Engine.*`;

    return markdown;
}

export function generateHtmlReport(
    memory: StructuredMemory,
    analysis: ConversationAnalysis | null,
    title?: string
): string {
    const reportTitle = title || "AI Conversation Analysis Report";
    const date = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric"
    });

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${reportTitle}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #2d3748;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            background: #ffffff;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #4299e1;
            padding-bottom: 1rem;
            margin-bottom: 2rem;
        }
        h1 {
            color: #1a365d;
            margin: 0 0 0.5rem 0;
            font-size: 2.5rem;
            font-weight: 700;
        }
        .date {
            color: #718096;
            font-style: italic;
            font-size: 1rem;
        }
        h2 {
            color: #2b6cb0;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 0.5rem;
            margin: 2rem 0 1rem 0;
            font-size: 1.8rem;
        }
        h3 {
            color: #3182ce;
            margin: 1.5rem 0 0.75rem 0;
            font-size: 1.3rem;
        }
        .toc {
            background: #f7fafc;
            padding: 1.5rem;
            border-radius: 8px;
            margin: 1.5rem 0;
            border-left: 4px solid #4299e1;
        }
        .toc h2 {
            margin-top: 0;
            border-bottom: none;
            color: #2d3748;
            font-size: 1.4rem;
        }
        .toc ul {
            margin: 0;
            padding-left: 1.5rem;
        }
        .toc li {
            margin: 0.3rem 0;
        }
        .toc a {
            color: #3182ce;
            text-decoration: none;
        }
        .toc a:hover {
            text-decoration: underline;
        }
        .section {
            margin: 1.5rem 0;
        }
        ul, ol {
            padding-left: 1.5rem;
        }
        li {
            margin: 0.5rem 0;
            line-height: 1.5;
        }
        .code-ref {
            background: #f1f5f9;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 0.9rem;
            color: #4a5568;
            border: 1px solid #e2e8f0;
        }
        .action-item {
            background: #f0fff4;
            border-left: 4px solid #48bb78;
            padding: 0.5rem;
            margin: 0.5rem 0;
            border-radius: 0 4px 4px 0;
        }
        .question {
            background: #fffbf0;
            border-left: 4px solid #ed8936;
            padding: 0.5rem;
            margin: 0.5rem 0;
            border-radius: 0 4px 4px 0;
        }
        .decision {
            background: #f0f4ff;
            border-left: 4px solid #4299e1;
            padding: 0.5rem;
            margin: 0.5rem 0;
            border-radius: 0 4px 4px 0;
        }
        .footer {
            text-align: center;
            margin-top: 3rem;
            padding-top: 2rem;
            border-top: 1px solid #e2e8f0;
            color: #718096;
            font-style: italic;
        }
        @media print {
            body { padding: 1rem; }
            .toc { background: none; border: 1px solid #ccc; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${reportTitle}</h1>
        <div class="date">Generated on ${date}</div>
    </div>

    <div class="toc">
        <h2>Table of Contents</h2>
        <ul>
            <li><a href="#executive-summary">Executive Summary</a></li>
            <li><a href="#detailed-analysis">Detailed Analysis</a></li>
            <li><a href="#key-points">Key Points</a></li>
            <li><a href="#structured-memory">Structured Memory</a>
                <ul>
                    <li><a href="#overview">Overview</a></li>
                    ${memory.topics.length > 0 ? '<li><a href="#topics">Topics Discussed</a></li>' : ''}
                    ${memory.decisions.length > 0 ? '<li><a href="#decisions">Decisions Made</a></li>' : ''}
                    ${memory.important_points.length > 0 ? '<li><a href="#important-points">Important Points</a></li>' : ''}
                    ${memory.code_references.length > 0 ? '<li><a href="#code-references">Code References</a></li>' : ''}
                    ${memory.assumptions.length > 0 ? '<li><a href="#assumptions">Assumptions</a></li>' : ''}
                    ${memory.unresolved_questions.length > 0 ? '<li><a href="#questions">Unresolved Questions</a></li>' : ''}
                    ${memory.action_items.length > 0 ? '<li><a href="#action-items">Action Items</a></li>' : ''}
                </ul>
            </li>
        </ul>
    </div>

    <div class="section">
        <h2 id="executive-summary">Executive Summary</h2>
        <p>${analysis?.summary || '<em>No executive summary available.</em>'}</p>
    </div>

    <div class="section">
        <h2 id="detailed-analysis">Detailed Analysis</h2>
        <div>${(analysis?.detailed || '<em>No detailed analysis available.</em>').replace(/\n\n/g, '</p><p>').replace(/^/, '<p>').replace(/$/, '</p>')}</div>
    </div>

    <div class="section">
        <h2 id="key-points">Key Points</h2>
        ${analysis?.keyPoints && analysis.keyPoints.length > 0 
            ? `<ol>${analysis.keyPoints.map(point => `<li>${point}</li>`).join('')}</ol>`
            : '<p><em>No key points extracted.</em></p>'
        }
    </div>

    <div class="section">
        <h2 id="structured-memory">Structured Memory</h2>

        <h3 id="overview">Overview</h3>
        <p>${memory.overview || '<em>No overview available.</em>'}</p>

        ${memory.topics.length > 0 ? `
        <h3 id="topics">Topics Discussed</h3>
        <ul>${memory.topics.map(topic => `<li>${topic}</li>`).join('')}</ul>
        ` : ''}

        ${memory.decisions.length > 0 ? `
        <h3 id="decisions">Decisions Made</h3>
        <div>${memory.decisions.map(decision => `<div class="decision">${decision}</div>`).join('')}</div>
        ` : ''}

        ${memory.important_points.length > 0 ? `
        <h3 id="important-points">Important Points</h3>
        <ul>${memory.important_points.map(point => `<li>${point}</li>`).join('')}</ul>
        ` : ''}

        ${memory.code_references.length > 0 ? `
        <h3 id="code-references">Code References</h3>
        <ul>${memory.code_references.map(ref => `<li><span class="code-ref">${ref}</span></li>`).join('')}</ul>
        ` : ''}

        ${memory.assumptions.length > 0 ? `
        <h3 id="assumptions">Assumptions</h3>
        <ul>${memory.assumptions.map(assumption => `<li>${assumption}</li>`).join('')}</ul>
        ` : ''}

        ${memory.unresolved_questions.length > 0 ? `
        <h3 id="questions">Unresolved Questions</h3>
        <div>${memory.unresolved_questions.map(question => `<div class="question">${question}</div>`).join('')}</div>
        ` : ''}

        ${memory.action_items.length > 0 ? `
        <h3 id="action-items">Action Items</h3>
        <div>${memory.action_items.map(item => `<div class="action-item">☐ ${item}</div>`).join('')}</div>
        ` : ''}
    </div>

    <div class="footer">
        This report was generated by the AI Conversation Portability Engine.
    </div>
</body>
</html>`;
}